apiVersion: v1
kind: Service
metadata:
  name: webaj
  labels:
    app: webaj
spec:
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: webaj
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webaj-pv-claim
  labels:
    app: webaj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webaj
  labels:
    app: webaj
spec:
  selector:
    matchLabels:
      app: webaj
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webaj
        tier: frontend
    spec:
      containers:
      - image: httpd
        name: webaj
        
        ports:
        - containerPort: 80
          name: webaj
        volumeMounts:
        - name: webaj-persistent-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: webaj-persistent-storage
        persistentVolumeClaim:
          claimName: webaj-pv-claim
